# coding: utf-8

"""
    Open Legal Data API

    With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website.  # noqa: E501

    OpenAPI spec version: v1
    Contact: hello@openlegaldata.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oldp_client
from oldp_client.models.inline_response2007 import InlineResponse2007  # noqa: E501
from oldp_client.rest import ApiException


class TestInlineResponse2007(unittest.TestCase):
    """InlineResponse2007 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007(self):
        """Test InlineResponse2007"""
        # FIXME: construct object with mandatory attributes with example values
        # model = oldp_client.models.inline_response2007.InlineResponse2007()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
