# coding: utf-8

"""
    Open Legal Data API

    With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website.  # noqa: E501

    OpenAPI spec version: v1
    Contact: hello@openlegaldata.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oldp_client
from oldp_client.models.case_marker import CaseMarker  # noqa: E501
from oldp_client.rest import ApiException


class TestCaseMarker(unittest.TestCase):
    """CaseMarker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaseMarker(self):
        """Test CaseMarker"""
        # FIXME: construct object with mandatory attributes with example values
        # model = oldp_client.models.case_marker.CaseMarker()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
