# coding: utf-8

"""
    Open Legal Data API

    With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website.  # noqa: E501

    OpenAPI spec version: v1
    Contact: api@openlegaldata.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oldp_client
from oldp_client.api.law_books_api import LawBooksApi  # noqa: E501
from oldp_client.rest import ApiException


class TestLawBooksApi(unittest.TestCase):
    """LawBooksApi unit test stubs"""

    def setUp(self):
        self.api = oldp_client.api.law_books_api.LawBooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_law_books_create(self):
        """Test case for law_books_create

        """
        pass

    def test_law_books_delete(self):
        """Test case for law_books_delete

        """
        pass

    def test_law_books_list(self):
        """Test case for law_books_list

        """
        pass

    def test_law_books_partial_update(self):
        """Test case for law_books_partial_update

        """
        pass

    def test_law_books_read(self):
        """Test case for law_books_read

        """
        pass

    def test_law_books_update(self):
        """Test case for law_books_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
