# coding: utf-8

"""
    Open Legal Data API

    With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website.  # noqa: E501

    OpenAPI spec version: v1
    Contact: api@openlegaldata.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oldp_client
from oldp_client.api.laws_api import LawsApi  # noqa: E501
from oldp_client.rest import ApiException


class TestLawsApi(unittest.TestCase):
    """LawsApi unit test stubs"""

    def setUp(self):
        self.api = oldp_client.api.laws_api.LawsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_laws_create(self):
        """Test case for laws_create

        """
        pass

    def test_laws_delete(self):
        """Test case for laws_delete

        """
        pass

    def test_laws_list(self):
        """Test case for laws_list

        """
        pass

    def test_laws_partial_update(self):
        """Test case for laws_partial_update

        """
        pass

    def test_laws_read(self):
        """Test case for laws_read

        """
        pass

    def test_laws_update(self):
        """Test case for laws_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
