# coding: utf-8

"""
    Open Legal Data API

    With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website.  # noqa: E501

    OpenAPI spec version: v1
    Contact: api@openlegaldata.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oldp_client
from oldp_client.api.token_auth_api import TokenAuthApi  # noqa: E501
from oldp_client.rest import ApiException


class TestTokenAuthApi(unittest.TestCase):
    """TokenAuthApi unit test stubs"""

    def setUp(self):
        self.api = oldp_client.api.token_auth_api.TokenAuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_token_auth_create(self):
        """Test case for token_auth_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
