# coding: utf-8

"""
    Open Legal Data API

    With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website.  # noqa: E501

    OpenAPI spec version: v1
    Contact: hello@openlegaldata.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oldp_client
from oldp_client.api.annotation_labels_api import AnnotationLabelsApi  # noqa: E501
from oldp_client.rest import ApiException


class TestAnnotationLabelsApi(unittest.TestCase):
    """AnnotationLabelsApi unit test stubs"""

    def setUp(self):
        self.api = oldp_client.api.annotation_labels_api.AnnotationLabelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_annotation_labels_create(self):
        """Test case for annotation_labels_create

        """
        pass

    def test_annotation_labels_delete(self):
        """Test case for annotation_labels_delete

        """
        pass

    def test_annotation_labels_list(self):
        """Test case for annotation_labels_list

        """
        pass

    def test_annotation_labels_partial_update(self):
        """Test case for annotation_labels_partial_update

        """
        pass

    def test_annotation_labels_read(self):
        """Test case for annotation_labels_read

        """
        pass

    def test_annotation_labels_update(self):
        """Test case for annotation_labels_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
